
spring:
  application:
    name: java_project
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://127.0.0.1:27017/java_projet
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG