server:
  port: 9090

spring:
  application:
    name: java_project
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://127.0.0.1:27017/java_projet
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
ai:
  service:
    url: http://localhost:5000
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
